version: '3.8'

services:
  app:
    container_name: kore-container
    tty: true
    stdin_open: true
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      HATENAID: sample
    depends_on:
      - db
    volumes:
      - $(pwd)/images:/work/images

  db:
    container_name: mysql-container
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: kore
      MYSQL_USER: kore
      MYSQL_PASSWORD: kore
      MYSQL_DATABASE: kore
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10 
    volumes:
      - ./db:/docker-entrypoint-initdb.d
