CREATE TABLE user (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    hatena_id VARCHAR(32) NOT NULL,
    wordcloud MEDIUMBLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE article (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    url TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE word (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE user_article (
    id INT UNSIGNED,
    user_id INT UNSIGNED NOT NULL,
    article_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (article_id) REFERENCES article(id)
);

CREATE TABLE article_word (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    article_id BIGINT UNSIGNED NOT NULL,
    word_id BIGINT UNSIGNED NOT NULL,
    word_count INT UNSIGNED NOT NULL,
    FOREIGN KEY (article_id) REFERENCES article(id),
    FOREIGN KEY (word_id) REFERENCES word(id)
);
